2022-09-22 17:27:31.215918: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-09-22 17:27:31.220829: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /software/cudnn-8.3.1-el8-x86_64/lib64
2022-09-22 17:27:31.220854: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-09-22 17:27:37.708065: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /software/cudnn-8.3.1-el8-x86_64/lib64
2022-09-22 17:27:37.708109: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-09-22 17:27:37.708130: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (midway3-0168.rcc.local): /proc/driver/nvidia/version does not exist
2022-09-22 17:27:37.708534: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "standard_variable.py", line 127, in <module>
    logXiH_NN_tf = tf.saved_model.load(outputdir   + 'logXiH_NN')
  File "/software/python-anaconda-2021.05-el8-x86_64/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 782, in load
    result = load_partial(export_dir, None, tags, options)["root"]
  File "/software/python-anaconda-2021.05-el8-x86_64/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 887, in load_partial
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/software/python-anaconda-2021.05-el8-x86_64/lib/python3.8/site-packages/tensorflow/python/saved_model/loader_impl.py", line 57, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
  File "/software/python-anaconda-2021.05-el8-x86_64/lib/python3.8/site-packages/tensorflow/python/saved_model/loader_impl.py", line 115, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: /project/lhansen/NN_midway3/output/WZVtilde_sigma_K_0040_sigma_Z_0014_sigma_V_0000_sigma_Vtilde_0100/chiUnderline_1000_a_e_0150_a_h_0050_gamma_e_0500_gamma_h_8000_psi_e_1500_psi_h_0500/trial_2_XiE_layers_3_XiH_layers_3_kappa_layers_3_points_size_2_iter_num_15/logXiH_NN/{saved_model.pbtxt|saved_model.pb}
2022-09-22 17:27:38.451822: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-09-22 17:27:38.456527: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /software/cudnn-8.3.1-el8-x86_64/lib64
2022-09-22 17:27:38.456552: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-09-22 17:27:42.821977: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /software/cudnn-8.3.1-el8-x86_64/lib64
2022-09-22 17:27:42.822950: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-09-22 17:27:42.822976: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (midway3-0168.rcc.local): /proc/driver/nvidia/version does not exist
2022-09-22 17:27:42.823404: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "standard_moments.py", line 148, in <module>
    Fe_NN, firstCoefsE_NN, secondCoefsE_NN, HJB_E_NN, Fh_NN, firstCoefsH_NN, secondCoefsH_NN, HJB_H_NN, kappa_min_NN = [np.load(outputdir +i+'.npy')  for i in load_list]
  File "standard_moments.py", line 148, in <listcomp>
    Fe_NN, firstCoefsE_NN, secondCoefsE_NN, HJB_E_NN, Fh_NN, firstCoefsH_NN, secondCoefsH_NN, HJB_H_NN, kappa_min_NN = [np.load(outputdir +i+'.npy')  for i in load_list]
  File "/software/python-anaconda-2021.05-el8-x86_64/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/project/lhansen/NN_midway3/output/WZVtilde_sigma_K_0040_sigma_Z_0014_sigma_V_0000_sigma_Vtilde_0100/chiUnderline_1000_a_e_0150_a_h_0050_gamma_e_0500_gamma_h_8000_psi_e_1500_psi_h_0500/trial_2_XiE_layers_3_XiH_layers_3_kappa_layers_3_points_size_2_iter_num_15/W_NN.npy'
